apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phonebill-front
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: phonebill.72.155.72.236.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: phonebill-front
                port:
                  number: 8080
