apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: phonebill

resources:
  - ../../base

patches:
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: cm-phonebill-front
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: phonebill-front
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: phonebill-front

images:
  - name: docker.io/hiondal/phonebill-front
    newTag: latest